version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5834:5432' # expose pg on port 5834 to not collide with pg from elswhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: life-tracker
volumes:
  db_data:
