import type { NextPage, GetServerSideProps } from 'next';
import { useSession, getSession } from 'next-auth/react';
import Head from 'next/head';

function SiteHead() {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default function Home() {
  const { data: session } = useSession();

  return (
    <div>
      <SiteHead />
      foobar
    </div>
  );
}

/**
 *  Note: By getting session and returning it as props, we allow NextAuth.js to
 *  pass the session and hydrate the page.
 *
 *  This prevents the "flickering" state of the first render assuming signed-out
 *  or loading state
 */
export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });

  return { props: { session } };
};
